/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stringxmltotextconverter.ui;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import stringxmltotextconverter.output.TextFileWriter;
import stringxmltotextconverter.output.XLFileWriter;
import stringxmltotextconverter.parser.StringXMLToHashConverter;

/**
 *
 * @author nsekhar
 */
public class MainUI extends javax.swing.JFrame
{

    private String xmlFileLocation;

    public MainUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelChoose = new javax.swing.JLabel();
        etFilePath = new javax.swing.JTextField();
        cbTextFile = new javax.swing.JCheckBox();
        cbXL = new javax.swing.JCheckBox();
        btnFileChooser = new javax.swing.JButton();
        labelOutput = new javax.swing.JLabel();
        btnParse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Strings.xml Extractor");
        setResizable(false);

        labelChoose.setText("Choose Strings.xml file");

        etFilePath.setText("");

        cbTextFile.setText("Text file");

        cbXL.setText("XL File");

        btnFileChooser.setText("Choose");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFileChooserActionPerformed(evt);
            }
        });

        labelOutput.setText("Output :");

        btnParse.setText("Parse");
        btnParse.setEnabled(false);
        btnParse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnParseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelOutput)
                                .addGap(18, 18, 18)
                                .addComponent(cbTextFile)
                                .addGap(18, 18, 18)
                                .addComponent(cbXL))
                            .addComponent(etFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFileChooser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnParse)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelChoose)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileChooser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTextFile)
                    .addComponent(cbXL)
                    .addComponent(labelOutput))
                .addGap(18, 18, 18)
                .addComponent(btnParse)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFileChooserActionPerformed
    {//GEN-HEADEREND:event_btnFileChooserActionPerformed
        final JFileChooser fc = new JFileChooser();
        final FileFilter filter = new FileNameExtensionFilter("Android Strings Filter", "xml");

        fc.setFileFilter(filter);
        int result = fc.showOpenDialog(null);

        switch (result)
        {
            case JFileChooser.APPROVE_OPTION:
                xmlFileLocation = fc.getSelectedFile().getAbsolutePath();
                btnParse.setEnabled(true);
                etFilePath.setText(fc.getSelectedFile().getAbsolutePath());
                break;

            default:
                btnParse.setEnabled(false);
                break;

        }
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void btnParseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnParseActionPerformed
    {//GEN-HEADEREND:event_btnParseActionPerformed
        boolean toText = cbTextFile.isSelected();
        boolean toXL = cbXL.isSelected();

        if (toText || toXL)
        {
            StringXMLToHashConverter st = new StringXMLToHashConverter(etFilePath.getText());
            st.parse();

            if (toText)
            {
                TextFileWriter txtWriter = new TextFileWriter();
                txtWriter.write(st.getStringList(), etFilePath.getText());
            }
            if (toXL)
            {
                XLFileWriter xlWriter = new XLFileWriter();
                xlWriter.write(st.getStringList(), etFilePath.getText());
            }
        }
    }//GEN-LAST:event_btnParseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnParse;
    private javax.swing.JCheckBox cbTextFile;
    private javax.swing.JCheckBox cbXL;
    private javax.swing.JTextField etFilePath;
    private javax.swing.JLabel labelChoose;
    private javax.swing.JLabel labelOutput;
    // End of variables declaration//GEN-END:variables
}
